"""schema_geometrie_parcelles

Revision ID: 9e4beb33aca7
Revises: dd2eb81adbdd
Create Date: 2026-08-17 21:01:31.316258
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9e4beb33aca7'
down_revision: Union[str, Sequence[str], None] = 'dd2eb81adbdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parcel', sa.Column('boundary_geojson', sa.Text(), server_default='', nullable=True))
    op.add_column('parcel', sa.Column('center_lat', sa.Numeric(precision=9, scale=6), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('center_lon', sa.Numeric(precision=9, scale=6), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('map_zoom', sa.Numeric(precision=4, scale=1), server_default='15', nullable=True))
    op.add_column('parcel', sa.Column('bbox_min_lat', sa.Numeric(precision=9, scale=6), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('bbox_min_lon', sa.Numeric(precision=9, scale=6), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('bbox_max_lat', sa.Numeric(precision=9, scale=6), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('bbox_max_lon', sa.Numeric(precision=9, scale=6), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('geometry_area_ha', sa.Numeric(precision=10, scale=2), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('geometry_vertex_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('parcel', sa.Column('geometry_source', sa.Enum('AUCUNE', 'GENEREE', 'DESSINEE', 'IMPORTEE', 'CADASTRE', name='geometrysource', native_enum=False, length=32), server_default='AUCUNE', nullable=True))
    op.add_column('parcel', sa.Column('geometry_srid', sa.Integer(), server_default='4326', nullable=True))
    op.add_column('parcel', sa.Column('geometry_color_hex', sa.String(length=9), server_default='#a3e635', nullable=True))
    op.add_column('parcel', sa.Column('geometry_updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('parcel', sa.Column('geometry_updated_by', sa.String(length=120), server_default='', nullable=True))
    op.add_column('parcel', sa.Column('geometry_notes', sa.Text(), server_default='', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parcel', 'geometry_notes')
    op.drop_column('parcel', 'geometry_updated_by')
    op.drop_column('parcel', 'geometry_updated_at')
    op.drop_column('parcel', 'geometry_color_hex')
    op.drop_column('parcel', 'geometry_srid')
    op.drop_column('parcel', 'geometry_source')
    op.drop_column('parcel', 'geometry_vertex_count')
    op.drop_column('parcel', 'geometry_area_ha')
    op.drop_column('parcel', 'bbox_max_lon')
    op.drop_column('parcel', 'bbox_max_lat')
    op.drop_column('parcel', 'bbox_min_lon')
    op.drop_column('parcel', 'bbox_min_lat')
    op.drop_column('parcel', 'map_zoom')
    op.drop_column('parcel', 'center_lon')
    op.drop_column('parcel', 'center_lat')
    op.drop_column('parcel', 'boundary_geojson')
    # ### end Alembic commands ###
