"""schema_employes_engins_maintenance

Revision ID: dd2eb81adbdd
Revises: 5ab50e3a7967
Create Date: 2026-08-17 20:18:13.038373
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd2eb81adbdd'
down_revision: Union[str, Sequence[str], None] = '5ab50e3a7967'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=False),
    sa.Column('last_name', sa.String(length=80), nullable=False),
    sa.Column('employee_code', sa.String(length=40), nullable=False),
    sa.Column('job_title', sa.String(length=120), nullable=False),
    sa.Column('contract_type', sa.Enum('CDI', 'CDD', 'SAISONNIER', 'APPRENTI', 'STAGE', 'PRESTATAIRE', name='contracttype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIF', 'CONGE', 'ARRET_MALADIE', 'FORMATION', 'SORTI', name='employeestatus', native_enum=False, length=32), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('hired_on', sa.Date(), nullable=True),
    sa.Column('contract_end_on', sa.Date(), nullable=True),
    sa.Column('weekly_hours', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('hourly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('team', sa.String(length=120), nullable=False),
    sa.Column('has_driving_licence', sa.Boolean(), nullable=False),
    sa.Column('has_phyto_certificate', sa.Boolean(), nullable=False),
    sa.Column('phyto_certificate_expiry', sa.Date(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requires_certification', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_skill_name')
    )
    op.create_table('employee_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DISPONIBLE', 'CONGE', 'ARRET', 'FORMATION', 'ASTREINTE', 'INDISPONIBLE', name='availabilitytype', native_enum=False, length=32), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('hours_per_day', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_all_day', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('DEBUTANT', 'INTERMEDIAIRE', 'AVANCE', 'EXPERT', name='skilllevel', native_enum=False, length=32), nullable=False),
    sa.Column('years_experience', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('certified_on', sa.Date(), nullable=True),
    sa.Column('certificate_expiry', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'skill_id', name='uq_employee_skill_pair')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('TRACTEUR', 'MOISSONNEUSE', 'PULVERISATEUR', 'SEMOIR', 'OUTIL_TRAVAIL_SOL', 'REMORQUE', 'IRRIGATION', 'MANUTENTION', 'VEHICULE', 'AUTRE', name='equipmentcategory', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('DISPONIBLE', 'EN_SERVICE', 'EN_MAINTENANCE', 'HORS_SERVICE', 'RESERVE', 'CEDE', name='equipmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('ownership', sa.Enum('PROPRIETE', 'LEASING', 'LOCATION', 'COPROPRIETE', 'PRESTATION', name='ownershiptype', native_enum=False, length=32), nullable=False),
    sa.Column('brand', sa.String(length=120), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=120), nullable=False),
    sa.Column('registration', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('power_hp', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('working_width_m', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('usage_unit', sa.Enum('HEURES', 'KILOMETRES', 'HECTARES', name='usageunit', native_enum=False, length=32), nullable=False),
    sa.Column('usage_counter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('residual_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('hourly_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fuel_consumption_l_h', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('storage_location', sa.String(length=120), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('inspection_expiry', sa.Date(), nullable=True),
    sa.Column('next_service_date', sa.Date(), nullable=True),
    sa.Column('next_service_counter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('service_interval_days', sa.Integer(), nullable=False),
    sa.Column('service_interval_counter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['responsible_id'], ['employee.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'REGLEMENTAIRE', 'AMELIORATION', name='maintenancekind', native_enum=False, length=32), nullable=False),
    sa.Column('trigger_basis', sa.Enum('CALENDRIER', 'COMPTEUR', 'MIXTE', name='triggerbasis', native_enum=False, length=32), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('interval_counter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tolerance_days', sa.Integer(), nullable=False),
    sa.Column('last_done_on', sa.Date(), nullable=True),
    sa.Column('last_done_counter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('next_due_on', sa.Date(), nullable=True),
    sa.Column('next_due_counter', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('estimated_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('checklist', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['employee.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('equipment_usage_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('used_on', sa.Date(), nullable=True),
    sa.Column('counter_start', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counter_end', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hours_used', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('fuel_liters', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.Enum('PREVENTIVE', 'CORRECTIVE', 'REGLEMENTAIRE', 'AMELIORATION', name='maintenancekind', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PLANIFIEE', 'EN_COURS', 'REALISEE', 'REPORTEE', 'ANNULEE', name='maintenancestatus', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Enum('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='maintenancepriority', native_enum=False, length=32), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('done_date', sa.Date(), nullable=True),
    sa.Column('counter_at_service', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('downtime_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('labor_hours', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('parts_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('external_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=160), nullable=False),
    sa.Column('invoice_reference', sa.String(length=120), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('failure_description', sa.Text(), nullable=False),
    sa.Column('work_performed', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['employee.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['schedule_id'], ['maintenance_schedule.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('intervention_id', sa.Integer(), nullable=True),
    sa.Column('parcel_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('RESPONSABLE', 'CONDUCTEUR', 'OPERATEUR', 'AIDE', 'OBSERVATEUR', name='assignmentrole', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('PROPOSEE', 'CONFIRMEE', 'EN_COURS', 'TERMINEE', 'ANNULEE', name='assignmentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('planned_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('actual_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('labor_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['intervention_id'], ['intervention.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_operation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parcel_id'], ['parcel.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('PIECE', 'MAIN_OEUVRE', 'CONSOMMABLE', 'SOUS_TRAITANCE', 'TRANSPORT', 'AUTRE', name='maintenancecosttype', native_enum=False, length=32), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=False),
    sa.Column('supplier', sa.String(length=160), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('incurred_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance_operation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_cost')
    op.drop_table('assignment')
    op.drop_table('maintenance_operation')
    op.drop_table('equipment_usage_log')
    op.drop_table('maintenance_schedule')
    op.drop_table('equipment')
    op.drop_table('employee_skill')
    op.drop_table('employee_availability')
    op.drop_table('skill')
    op.drop_table('employee')
    # ### end Alembic commands ###
